Moved sheet Ids and updated other files
CreativeSolutionsGroup/smart-events-kiosk-backend pull request #38
Opened 2022-09-13 16:26 UTC by SebastianNeiswanger

closes #25

2022-09-13 17:13 UTC, SpBills requested changes

2022-09-13 17:13 UTC, SpBills commented on src/utils/sheetID.ts
> +export const EVENT_SHEET_ID = "EVENTS";
I noticed that there are a bunch of files in the utils folder. First of all, our file naming scheme is snake_case. 

Next, don't have these be in their own file but instead put them in something applicable like `sheets.ts`

2022-09-13 17:13 UTC, SpBills commented on src/utils/sheetID.ts
> +export const EVENT_SHEET_ID = "EVENTS";
So, please rename all the files to their snake_case equivalent.

2022-09-13 18:06 UTC, SebastianNeiswanger commented
Renamed util files and moved the ids to sheets.ts

2022-09-19 12:15 UTC, SpBills approved these changes
LGTM

2022-09-19 12:15 UTC, merged